---
title: "PresidentSpeech"
author:
- Steven Tran
- Matthew Ciaramitaro
date: "April 4, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidytext)
library(tidyverse)
library(stringr)
library(foreach)
options(dplyr.print_max = 1e9)
```
```{r}
purl("bush41 first state of the union.txt", output = "Bush.R")
purl("JFK first state of the union.txt", output = "JFK.R")
#source("Bush.R")
#source("JFK.R")
nrc <- get_sentiments("nrc")
View(nrc)
JFK <- data.frame(readLines("JFK.R"))
BUS <- data.frame(readLines("Bush.R"))

colnames(JFK) <- c("text")
colnames(BUS) <- c("text")

JFK <- JFK %>% mutate(President = "JFK")
BUS <- BUS %>% mutate(President = "Bush")

JFK[, 1] <- as.character(JFK[, 1])
BUS[, 1] <- as.character(BUS[, 1])

DATA <- JFK %>% # TOTAL COUNT
  rbind(BUS) %>%
  unnest_tokens(word, text) %>%
  inner_join(nrc) %>%
  count(word, sort = TRUE)
DATAJ <- JFK %>% # JFK COUNT
  unnest_tokens(word, text) %>%
  inner_join(nrc) %>%
  count(word, sort = TRUE)
DATAB <- BUS %>% # BUSH COUNT
  unnest_tokens(word, text) %>%
  inner_join(nrc) %>%
  count(word, sort = TRUE)
# View(DATA)
# View(DATAJ)
# View(DATAB)

# We should use these 3 tables to determine % share JFK and BUSH have of total
joined <- DATA %>% full_join(DATAJ, by="word") %>% full_join(DATAB, by="word") 
#puts words and counts for total, bush, and kennedy in seperate columns
colnames(joined) <- c("word","Total", "JFK", "Bush") #name columns
nums <- tail(colnames(joined), -1)
joined <- mutate_at(joined, .vars=vars(nums), .funs=funs(replace(.,is.na(.), 0)) ) #replace na with 0
print(joined)
View(joined)

```

TODO: DISCUSS RESULTS OF TABLE

```{r}
#now we must divide the JFK and BUS cols by the total row
#percents <- joined %>% mutate_at(.vars=vars("JFK", "Bush"), . = . / Total)
percents <- joined %>% mutate(JFK = JFK / Total * 100) %>% mutate(Bush = Bush / Total * 100) %>% select(word, JFK, Bush)
colnames(percents) <- c("word", "JFK (%combined)", "Bush (%combined)") #name columns
#View(percents)
print(percents)
# We should count differences in top 10 words
top10jfk <- head(DATAJ, 10)[1] # top 10 words for jfk
top10bus <- head(DATAB, 10)[1] # top 10 words for bush
compare <- top10jfk %>%
  mutate(inTop10Bus = word %in% top10bus[[1]])
# View(top10jfk)
top10merged <- top10jfk %>% rbind(top10bus) %>% distinct()
insct <- top10jfk %>% intersect(top10bus)
#View(insct)
numsame <- nrow(insct)
print(paste("The number of words that did not change in the top 10 is ", numsame))
print("The following words remained in the top 10 most-used for both speeches:") 
print(insct$word)
```
We now perform sentiment analysis on these words.

```{r}
get_sentimentss <- function(df, sentiments, na.rm=T){
  #given a list of sentiments, cross references words in the data frame with list, may remove NA rows
  #NA rows are ones where the df contains a word which is not in the list of words/sentiments nrc
  nrc <- filter(nrc, sentiment %in% sentiments)
  ds <- df %>% left_join(nrc, by="word")
  if(na.rm){
    ds <- ds[complete.cases(ds), ]
  }
  return(ds)
} 
sentiments <- c("joy", "anger", "anticipation")
top10bussent <- get_sentimentss(top10bus, sentiments)
top10jfksent <- get_sentimentss(top10jfk, sentiments)
View(top10jfksent)



# Now let's calculate the percent occurence of each sentiment in top10 speech and overall.
get_pct_occur <- function(df, sentiments){
  #get df of pct occurence for each sentiment in a column dataframe
  occ <- as.data.frame(sentiments)
  n = nrow(df)
  l <- length(sentiments)
  occ$occurrences <- foreach(s= sentiments) %do% (nrow(df %>% select("sentiment") %>% filter(sentiment == s)) / n*100)
  return(occ)
}

pctocc_bush <- get_pct_occur(top10bussent, sentiments) # percent each sentiment occurs in top 10 most used words
pctocc_jfk <- get_pct_occur(top10jfksent, sentiments) 

#for overall let's get both the weighted overall sentiment, and the average for unique words
bussent <- get_sentimentss(DATAB,sentiments)
jfksent <- get_sentimentss(DATAJ, sentiments)
pct_overall_bush <- get_pct_occur(bussent,sentiments)
pct_overall_jfk <- get_pct_occur(jfksent,sentiments)
View(pct_overall_jfk)
View(pct_overall_bush)


# Sentiment Analysis
JFKSentiments <- JFK %>%
  unnest_tokens(word, text) %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
print(paste("Overall sentiment for JFK is ", sum(JFKSentiments$sentiment)))

BUSSentiments <- BUS %>%
  unnest_tokens(word, text) %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
print(paste("Overall sentiment for BUS is ", sum(BUSSentiments$sentiment)))

JFKSentimentsWeighted <- JFKSentiments %>% 
  mutate(weighted = sentiment/sum(sentiment))

BUSSentimentsWeighted <- BUSSentiments %>% 
  mutate(weighted = sentiment/sum(sentiment))
```
TODO Now let's analyze the difference between sentiment occurence in bush's and jfks speeches
